from typing import Protocol, Iterable, Optional, runtime_checkable
from app.domain.entities import Video, VideoJob


@runtime_checkable
class VideoRepositoryPort(Protocol):
    def add(self, v: Video) -> None: ...
    def get(self, video_id: str) -> Optional[Video]: ...


@runtime_checkable
class JobRepositoryPort(Protocol):
    def add(self, j: VideoJob) -> None: ...
    def get(self, job_id: str) -> Optional[VideoJob]: ...
    def update(self, j: VideoJob) -> None: ...
    def list_by_user(self, user_id: str) -> Iterable[VideoJob]: ...
