from typing import Protocol, BinaryIO


class StoragePort(Protocol):
    def save_upload(self, file_stream: BinaryIO, filename: str) -> str: ...
    def save_artifact(self, local_path: str) -> str: ...
    def make_temp_dir(self, prefix: str) -> str: ...
    def resolve_path(self, ref: str) -> str: ...
