name: PR Validation

on:
  pull_request:
    branches: [ main, master ]

env:
  SONAR_TOKEN: "347e4f4ccde61a3371b42eb5f7525652007b8953"

jobs:
  build_and_test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 coverage

      - name: Lint & fix com Ruff
        run: ruff check --fix .

      - name: Run tests and generate coverage
        run: |
          pytest --cov=app --cov-report=term --cov-report=xml --disable-warnings --cov-fail-under=70

      - name: Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  ssonar_scan:
      needs: build_and_test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Download coverage report
          uses: actions/download-artifact@v4
          with:
            name: coverage-report
        - name: Check coverage file
          run: |
            echo "Conteúdo de coverage.xml"
            cat coverage.xml

        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@v2
          env:
            SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          with:
            projectBaseDir: .